on: ["push", "pull_request"]

name: Integration Tests

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Use Node.js 10.x
      uses: actions/setup-node@master
      with:
        version: 10.x

    - name: Install mocha and run it
      run: |
        npm install -g mocha
        mocha
